In [1]:
import numpy as np


In [2]:
a=np.array([1,5,10])
print(a)

[ 1  5 10]


In [4]:
b=np.array([[1,7,20],[5,8,9]])
print(b)

[[ 1  7 20]
 [ 5  8  9]]


In [5]:
a.ndim

1

In [6]:
b.shape

(2, 3)

In [7]:
a.dtype

dtype('int32')

In [8]:
x=np.array([1.0,5.4,10.42])
x.dtype

dtype('float64')

In [9]:
print(b)

[[ 1  7 20]
 [ 5  8  9]]


In [10]:
b[0,2]

20

In [11]:
b[1,1]

8

In [12]:
b[0,1:]

array([ 7, 20])

In [13]:
b[1,1]=18

In [15]:
print(b)

[[ 1  7 20]
 [ 5 18  9]]


In [16]:
b

array([[ 1,  7, 20],
       [ 5, 18,  9]])

In [17]:
dizi_s=np.zeros((2,3))
dizi_s

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
dizi1=np.full((3,4),50)
dizi1

array([[50, 50, 50, 50],
       [50, 50, 50, 50],
       [50, 50, 50, 50]])

In [22]:
dizi2=np.random.rand(2,3)
dizi2

array([[0.66175683, 0.20012058, 0.03394428],
       [0.91474114, 0.6920863 , 0.05128028]])

In [24]:
dizi3=np.random.randint(0,100,size=(2,3))

dizi3

array([[54, 99, 79],
       [ 6, 34,  0]])

In [25]:
a=np.array([1,2,3])
b=a
b[0]=90
print(a)

[90  2  3]


In [27]:
a=np.array([1,2,3])
b=a.copy()
b[0]=90
print(a)
print(b)

[1 2 3]
[90  2  3]


In [28]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [29]:
a+4

array([5, 6, 7, 8])

In [30]:
a*2

array([2, 4, 6, 8])

In [31]:
a**2

array([ 1,  4,  9, 16])

In [32]:
a.dtype

dtype('int32')

In [33]:
dizi4=np.array([[1,2,3],[4,5,6]])
dizi4

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
np.min(dizi4)

1

In [35]:
np.max(dizi4)

6

In [36]:
np.sum(dizi4)

21

In [38]:
filedata=np.genfromtxt('ornek.txt',delimiter=',')
filedata=filedata.astype('int32')
print(filedata)

[[1 2 3 4 5 6 7]
 [8 9 7 8 9 9 8]
 [3 3 3 5 7 9 0]]


In [39]:
filedata[1,2]

7